### ISSUE TITLE
Merge server and blockchain

### ISSUE THREAD

**Issue by VilhelmSeip** [Altinn/summer-camp-2023#95]

**Comment by emilk2001** [comment]
const express = require('express');
const ethers = require('ethers');
const path = require('path');
const fs = require('fs');
const cors = require('cors');
const {registerCredential} = require("./services/registerCredential.js");
const Web3 = require('web3');

const app = express();
const port = 5000;

const jsonFilePath = path.join(__dirname, 'academic.json');

app.use(cors());
app.use(express.json());



app.post('/format-verifiable-credential',  (req, res) => {
    // Assuming we receive information in the request body
   // const { name, email, id } = req.body;
   try {
    console.log("received request body: ", req.body);
  const { id } = req.body;
  console.log("Calling registerCredential with ID:", id);
   
  
   
    const result =  registerCredential({ id });
    console.log("registerCredential result:", result);

    // Create our verifiable credential JSON object
    /*const verifiableCredential = {
      '@context': 'https://www.w3.org/2018/credentials/v1',
      type: 'VerifiableCredential',
      issuer: 'https://example.com/issuer', // Change this to the actual issuer URL
      issuanceDate: new Date().toISOString(),
      credentialSubject: {
        name,
        email,
        id,
      },
    };*/


  
    // You can add more properties and customizations as needed
  
    // Send the verifiable credential JSON in the response
    res.json(result)
   } catch (error) {
    console.error("Error during verification");
    res.status(500).json({ error: "failed to register credential"})
    
   }
   
  
  
  });

  app.post('/submitForm', (req, res) => {
    const formData = req.body;
    // Do whatever you want with the formData here (e.g., save it to a database)
    console.log(formData);
    res.status(200).send('Form data received successfully!');
  });

  app.get('/api/data', (req, res) => {
    fs.readFile(jsonFilePath, 'utf8', (err, data) => {
        if (err) {
            console.error("Error reading file: " + err);
            return res.status(500).json({ error: "Failed to read data from the JSON file" });
        }

        try {
            const jsonData = JSON.parse(data);
            return res.json(jsonData);
        } catch (parseError) {
            console.error("Failed parsing JSON: " + parseError);
            return res.status(500).json({ error: "Failed to parse data from the JSON file" });
        }
    });
});



/*app.get('/api', (req, res) => {
    res.json({ "users": ["John", "Jane", "Mary", "Sarah"] });
});*/


// Start the server
app.listen(port, () => {
  console.log(`Server running on http://localhost:${port}`);
});
